website/main/__init__.py
from flask import Blueprint

bp = Blueprint("main", __name__)

from website.main import routes

website/main/routes.py
from website.main import bp
from flask import render_template, request, flash, redirect, url_for, current_app
from flask_login import login_required
from flask_login import current_user
from datetime import datetime
from website.models import db, User, Post, Comment
from website.main.form import EditProfile, PostForm, CommentForm, PostUpdate

@bp.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()

@bp.route("/", methods=["GET", "POST"])
@login_required
def index():
    page = request.args.get('page', 1, type=int)
    posts = current_user.followed_posts().paginate(
        page=page, per_page=current_app.config["POSTS_PER_PAGE"]
    )
    next_url = url_for('main.index', page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('main.index', page=posts.prev_num) \
        if posts.has_prev else None
    return render_template("main/index.html", title="Home", \
        posts=posts.items, next_url=next_url, prev_url=prev_url)

@bp.route("/explore")
def explore():
    page = request.args.get("page", 1, type=int)
    posts = Post.all_posts().paginate(
        page=page, per_page=current_app.config["POSTS_PER_PAGE"]
    )
    next_url = url_for('main.explore', page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('main.explore', page=posts.prev_num) \
        if posts.has_prev else None
    return render_template('main/index.html', posts=posts.items, title="Explore", \
        next_url=next_url, prev_url=prev_url)

@bp.route("/upload_post", methods=["GET", "POST"])
@login_required
def upload_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, image_url=form.image_url.data, \
            category=form.category.data, price=form.price.data,\
                detail=form.detail.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash("Đã đăng lên trang chủ.")
        return redirect(url_for("main.index"))
    return render_template('main/upload_post.html', title="post", form=form)


@bp.route("/user/<id>")
def user(id):
    user = User.query.filter_by(id=id).first_or_404()
    page = request.args.get("page", 1, type=int)
    posts = user.my_posts().paginate(
        page=page, per_page=current_app.config["POSTS_PER_PAGE"]
    )
    next_url = url_for('main.user', id=id , page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('main.user', id=id , page=posts.prev_num) \
        if posts.has_prev else None
    return render_template("main/user.html", user=user, posts=posts.items, \
         title="Profile", next_url=next_url, prev_url=prev_url)

@bp.route("/edit_profile", methods=["GET", "POST"])
@login_required
def edit_profile():
    form = EditProfile()
    if form.validate_on_submit():
        current_user.username=form.username.data
        current_user.about_me=form.about_me.data
        db.session.commit()
        flash("Thay đổi đã được lưu.")
        return redirect(url_for('main.user', id=current_user.id))
    elif request.method == "GET":
        form.about_me.data = current_user.about_me
        form.username.data = current_user.username
    return render_template('main/edit_profile.html', title="Edit profile", \
        form=form)

@bp.route("/follow/<id>")
@login_required
def follow(id):
    user = User.query.filter_by(id=id).first()
    if user is None:
        flash("Không tìm thấy người dùng")
        return redirect(url_for('main.index'))
    elif user == current_user:
        flash("Bạn không thể tự theo dõi chính mình!")
        return redirect(url_for('main.user', id=id))
    current_user.follow(user)
    db.session.commit()
    flash('Bạn đang theo dõi %s' % user.username)
    return redirect(url_for('main.user', id=id))

@bp.route('/unfollow/<id>')
@login_required
def unfollow(id):
    user = User.query.filter_by(id=id).first()
    if user is None:
        flash("Không tìm thấy người dùng")
        return redirect(url_for('main.index'))
    elif user == current_user:
        flash("Bạn không thể bỏ theo dõi chính mình!")
        return redirect(url_for('main.user', id=id))
    current_user.unfollow(user)
    db.session.commit()
    flash('Bạn đã bỏ theo dõi %s' % user.username)
    return redirect(url_for('main.user', id=id))

@bp.route('/post_detail/<post_id>', methods=["GET", "POST"])
def post_detail(post_id):
    form = CommentForm()
    if form.validate_on_submit():
        if not current_user.is_authenticated:
            flash("Bạn phải đăng nhập trước khi sử dụng chức năng này.")
            return redirect(url_for('auth.login'))
        c = Comment(comment=form.comment.data, post_id=post_id, user_id=current_user.id)
        db.session.add(c)
        db.session.commit()
        flash("Đã thêm một bình luận vào bài viết")
        return redirect(url_for('main.post_detail', post_id=post_id)) 
    post = Post.query.filter_by(id=post_id).first_or_404()
    page = request.args.get('page', 1, type=int)
    comments = post.comments.order_by(Comment.timestamp.desc()).paginate(
        page=page, per_page=current_app.config["POSTS_PER_PAGE"]
    )
    next_url = url_for('main.post_detail', post_id=post_id, page=comments.next_num) \
        if comments.has_next else None
    prev_url = url_for('main.post_detail', post_id=post_id, page=comments.prev_num) \
        if comments.has_prev else None
    return render_template('main/post_detail.html', title="Post detail", post=post, \
        form=form, comments = comments, next_url=next_url, prev_url=prev_url)

@bp.route('/edit_post/<post_id>', methods=["GET", "POST"])
@login_required
def edit_post(post_id):
    post = Post.query.filter_by(id=post_id).first_or_404()
    if current_user != post.author:
        flash('Bạn không thể chỉnh sửa bài viết này!')
        return redirect(url_for('main.explore'))
    form = PostUpdate()
    if form.validate_on_submit():
        post.title = form.title.data
        post.image_url = form.image_url.data
        post.category = form.category.data
        post.price = form.price.data
        post.detail = form.detail.data
        post.status = 1 if form.status.data == 'Đã bán' else 0
        db.session.add(post)
        db.session.commit()
        flash('Thay đổi đã được lưu.')
        return redirect(url_for('main.post_detail', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.image_url.data = post.image_url
        form.category.data = post.category
        form.price.data = post.price
        form.detail.data = post.detail
        form.status.data = 'Chưa bán' if post.status == 0 else 1
    return render_template('main/edit_post.html', title='Edit post', \
        form = form)

@bp.route('/selled/<user_id>')
def selled(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    page = request.args.get('page', 1, type=int)
    posts = user.selled().paginate(page=page, \
        per_page=current_app.config["POSTS_PER_PAGE"])
    next_url = url_for('main.index', page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('main.index', page=posts.prev_num) \
        if posts.has_prev else None
    return render_template('main/selled.html', title='selled', \
        posts=posts, next_url=next_url, prev_url=prev_url)

    

website/templates/main/_comment.html
<p><a href="{{ url_for('main.user', id=comment.author.id) }}"><img style="border-radius: 50%;" src="{{ post.author.avatar(20) }}" alt="Avatar" /> {{ comment.author.username }}</a></p>
<p>{{ comment.comment }}<br>{{ moment(comment.timestamp).fromNow() }}</p>

website/templates/main/_post.html
<table class="table table-hover">
    <tr>
        <td></td>
        <td>
            <a href="{{ url_for('main.post_detail', post_id=post.id) }}">
                <img style="width: 200px; height: 200px" src="{{ post.image_url }}" onerror="this.src='https://csp-clients.s3.amazonaws.com/easttexasspa/wp-content/uploads/2021/06/no-image-icon-23485.png'">
            </a>
        </td>
    </tr>
    <tr>
        <td></td>
        <td>
            {% if post.title %}
                <p>{{ post.title[0:30] }}</p>
            {% endif %}
            {% if post.price %}
                <p>{{ post.price }} 000 VNĐ</p>
            {% endif %}
            <a href="{{ url_for('main.user', id=post.author.id) }}">
                <img style="border-radius: 50%;" src="{{ post.author.avatar(20) }}" alt="Avatar" />
            </a>
            <a href="{{ url_for('main.user', id=post.author.id) }}">
                {{ post.author.username }}
            </a><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            {{ moment(post.timestamp).fromNow() }}
        </td>
    </tr>
</table>

website/templates/main/edit_post.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block web_content %}
    <h1>Chỉnh sửa trang cá nhân</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

website/templates/main/edit_profile.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block web_content %}
    <h1>Chỉnh sửa trang cá nhân</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

website/templates/main/index.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block web_content %}
    {% if current_user.is_authenticated %}
        <h1>Xin chào, {{ current_user.username }}</h1>
    {% endif %}
    {% if form %}
        <div class="row">
            <div class="col-md-4">
                {{ wtf.quick_form(form) }}
            </div>
        </div>
    {% endif %}
    {% if posts: %}
        {% for post in posts %}
            {% include "main/_post.html" %}
        {% endfor %}
    {% endif %}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">←</span> Mới hơn
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    Cũ hơn <span aria-hidden="true">→</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

website/templates/main/post_detail.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block web_content %}
<table class="table table-hover">
    <tr>
        <td>
            <img style="width: 400px; height: 400px" src="{{ post.image_url }}" onerror="this.src='https://csp-clients.s3.amazonaws.com/easttexasspa/wp-content/uploads/2021/06/no-image-icon-23485.png'">
        </td>
        <td>
            <ul>
                {% if post.title %}
                    <li>Mô tả: {{ post.title }}</li>
                {% endif %}
                {% if post.category %}
                    <li>Danh mục: {{ post.category }}</li>
                {% endif %}
                {% if post.detail %}
                    <li>Chi tiết: {{ post.detail }}</li>
                {% endif %}
                {% if post.price %}
                    <li>Giá: {{ post.price }}.000 VNĐ</li>
                {% endif %}
                {% if post.status == 1 %}
                    <li>Tình trạng: Đã bán</li>
                {% else %}
                    <li>Tình trạng: Chưa bán</li>
                    {% endif %}
                {% if current_user == post.author %}
                    <li>
                        <a href="{{ url_for('main.edit_post', post_id=post.id) }}">Edit post</a>
                    </li>
                {% endif %}
                <li>
                    <a href="{{ url_for('main.user', id=post.author.id) }}">
                        <img style="border-radius: 50%;" src="{{ post.author.avatar(20) }}" alt="Avatar" />
                    </a>
                    <a href="{{ url_for('main.user', id=post.author.id) }}">
                        {{ post.author.username }}
                    </a><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    {{ moment(post.timestamp).fromNow() }}
                </li>
            </ul>
            <div class="row">
                <div class="col-md-4">
                    {{ wtf.quick_form(form) }}
                </div>
            </div>
        </td>
    </tr>
    <tr>
        <td></td>
        <td>
            {% for comment in comments %}
                <p>{% include "main/_comment.html" %}</p>
            {% endfor %}
        </td>
    </tr>
</table>
<nav aria-label="...">
    <ul class="pager">
        <li class="previous{% if not prev_url %} disabled{% endif %}">
            <a href="{{ prev_url or '#' }}">
                <span aria-hidden="true">←</span> Mới hơn
            </a>
        </li>
        <li class="next{% if not next_url %} disabled{% endif %}">
            <a href="{{ next_url or '#' }}">
                Cũ hơn <span aria-hidden="true">→</span>
            </a>
        </li>
    </ul>
</nav>

{% endblock %}

website/templates/main/selled.html
{% extends 'base.html' %}
{% block web_content %}
    {% if posts %}
        {% for post in posts %}
            {% include "main/_post.html" %}
        {% endfor %}
    {% endif %}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">←</span> Mới hơn
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    Cũ hơn <span aria-hidden="true">→</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

website/templates/main/upload_post.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block web_content %}
    <h1>Post</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
    <p><a href="{{ url_for('main.index') }}">Cancel</a></p>
{% endblock %}

website/templates/main/user.html
{% extends "base.html" %}
{% block web_content %}
    <table>
        <tr valign="top">
            <td><img style="border-radius: 50%;" src="{{ user.avatar(175) }}" alt="Avatar"></td>
            <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
            <td>
                <br>
                <p style="font-size: 100; font-weight: 500; font: bolder;">
                    <b>{{ user.username }}</b>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    {% if user==current_user %}
                        <a href="{{ url_for('main.edit_profile') }}">Chỉnh sửa hồ sơ</a>
                    {% elif not current_user.is_authenticated %}
                        <a href="{{ url_for('main.follow', id=user.id) }}">Theo dõi</a>
                    {% elif current_user.is_following(user) %}
                        <a href="{{ url_for('main.unfollow', id=user.id) }}">Bỏ theo dõi</a>
                    {% else %}
                        <a href="{{ url_for('main.follow', id=user.id) }}">Theo dõi</a>
                    {% endif %}
                </p>
                <p>
                    <b>{{ user.posts.count() }}</b> Bài đăng
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="{{ url_for('main.selled', user_id=user.id) }}">
                        <b>{{ user.posts.filter_by(status = 1).count() }}</b> Đã bán
                    </a>
                    <br>
                    <b>{{ user.followers.count() }}</b> Người theo dõi
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <b>{{ user.followed.count() }}</b> Đang theo dõi
                </p>
                <p>Email: {{ user.email }}</p>
                {% if user.about_me %}
                    <p>{{ user.about_me }}</p>
                {% endif %}
                {% if user.last_seen %}
                    <p>Lần HĐ cuối: {{ moment(user.last_seen).format('L') }}</p>
                {% endif %}
            </td>
        </tr>
    </table>
    <hr>
{% for post in posts %}
    {% include "main/_post.html" %}
{% endfor %}
<nav aria-label="...">
    <ul class="pager">
        <li class="previous{% if not prev_url %} disabled{% endif %}">
            <a href="{{ prev_url or '#' }}">
                <span aria-hidden="true">←</span> Mới hơn
            </a>
        </li>
        <li class="next{% if not next_url %} disabled{% endif %}">
            <a href="{{ next_url or '#' }}">
                Cũ hơn <span aria-hidden="true">→</span>
            </a>
        </li>
    </ul>
</nav>
{% endblock %}